### ISSUE TITLE
Automatic static optimization automatic opt-out problem.

### ISSUE THREAD

**Issue by amiroff** [xeoneux/next-dark-mode#10]
Thanks for the great library.

Using next-dark-mode causes Next.js app to render pages server-side, thus significantly slowing down first content render by implementing `getInitialProps`. Is there a way to avoid it?

Here's the build output:

```
$ next build
info  - Loaded env from D:\Code\NextBook\.env.local
info  - Creating an optimized production build
info  - Compiled successfully 
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does 
not opt-out pages with `getStaticProps`
Read more: https://err.sh/next.js/opt-out-auto-static-optimization
```

Usage example: [NextBook](https://github.com/amiroff/NextBook/blob/master/pages/_app.jsx)

**Comment by amiroff** [comment]
Sorry for not checking this upfront, it has already been discussed to no avail. Closing this ticket now.

**Comment by xeoneux** [comment]
Hi @amiroff 
Would you like this library to have an option of using local storage for storing dark mode preferences so that it can be used with automatic static optimisation?

**Comment by amiroff** [comment]
Hello @xeoneux , that would be perfect tbh, but a mention in docs/readme warning that it could break static builds would prevent surprises 🥇
