### ISSUE TITLE
Cannot use the hook with styled-components

### ISSUE THREAD

**Issue by ghost** [xeoneux/next-dark-mode#7]
disclaimer: I'm new to next. 

```
  const {
    autoModeActive,
    autoModeSupported,
    darkModeActive,
    switchToAutoMode,
    switchToDarkMode,
    switchToLightMode,
  } = darkMode
```

this works well in`_app`, but when I try to use this as hook in a component, I can't use the following functions:

```
const {
    switchToAutoMode,  // function - toggles the auto mode on
    switchToDarkMode,  // function - toggles the dark mode on
    switchToLightMode, // function - toggles the light mode on
  } = useDarkMode()
  console.log(useDarkMode())
```

**Comment by xeoneux** [comment]
Hi @tchret 
I saw that removing the provider stopped the functions from working.
I have removed it in the new update, please try the example now, you can use the hooks normally.
Thanks
